import type { Metadata } from 'next'
import { firaMono } from '@/app/fonts'
import './globals.css'
import { Providers } from './providers'
import Header from '@/app/components/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={'light ' + `${firaMono.className}`}>
        <Providers>
          <Header />
          {children}
          <footer></footer>
        </Providers>
      </body>
    </html>
  )
}
