import type { Metadata } from 'next'
import { firaMono } from '@/app/fonts'
import './globals.css'
import { Providers } from './providers'
import Header from '@/app/components/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

/**
 * about suppressHydrationWarning
 * https://nextjs.org/docs/messages/react-hydration-error
 * https://github.com/vercel/next.js/discussions/22388#discussioncomment-8271118
 */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${firaMono.className}`} suppressHydrationWarning>
        <Providers>
          <Header />
          {children}
          <footer></footer>
        </Providers>
      </body>
    </html>
  )
}
